export const USER_ROLE = {
    superAdmin: 'superAdmin',
    admin: 'admin',
    seller: 'seller',
    user: 'user'
    
} as const


export const parentCategoryNames: string[] = [
    'Electronics',
    'Mobile Accessories',
    'Computers & Laptops',
    'Televisions & Home Entertainment',
    'Kitchen Appliances',
    'Power Tools',
    'Hardware & Construction',
    'Lighting & Electrical',
    'Cables & Wires',
    'Gaming & Consoles',
];






export const parentToSubCategories = {
  "Electronics": [
    "Smartphones & Tablets",
    "Feature Phones",
    "Monitors & Displays",
    "Cameras & Photography",
    "DSLRs & Mirrorless Cameras",
    "Drones & Action Cameras",
    "Wearables & Smartwatches",
    "Audio Devices",
    "Home Audio Systems",
    "Projectors & Accessories",
    "VR Headsets & Gaming Gear",
    "E-Readers & Tablets",
    "Car Electronics",
    "Smart Home Devices",
    "Networking Devices",
    "Calculators & Electronic Gadgets",
    "Office Electronics",
    "Walkie Talkies & Communication Devices",
    "Portable Media Players",
    "Headphones & Speakers"
  ],

  "Mobile Accessories": [
    "Phone Cases & Covers",
    "Screen Protectors",
    "Chargers & Power Adapters",
    "Power Banks",
    "Earphones & Headphones",
    "Bluetooth Speakers",
    "Car Mounts & Holders",
    "USB Cables & Connectors",
    "Selfie Sticks & Tripods",
    "Smartwatch Bands",
    "Wireless Charging Pads",
    "Phone Camera Lenses",
    "Phone Stands & Holders",
    "Gaming Controllers for Mobiles",
    "Stylus Pens",
    "Mobile Cleaning Kits",
    "SIM Card Adapters & Tools",
    "Portable Phone Fans & Cooling Accessories",
    "Phone Wallets & Pouches",
    "VR Headsets for Mobile"
  ],

  "Computers & Laptops": [
    "Gaming Laptops",
    "Business Laptops",
    "Laptops",
    "Desktop PCs",
    "Desktops",
    "Monitors",
    "Keyboards & Mice",
    "RAM & Graphics Cards",
    "External Hard Drives & SSD",
    "UPS & Power Solutions",
    "Docking Stations",
    "Cooling Pads",
    "Motherboards",
    "Processors",
    "GPU & Graphics Cards",
    "Laptop Bags & Sleeves",
    "Laptop Stands",
    "Networking Cards & Adapters",
    "Printers",
    "Scanners"
  ],

  "Televisions & Home Entertainment": [
    "LED TVs",
    "Smart TVs",
    "4K & OLED TVs",
    "Home Theater Systems",
    "Soundbars",
    "Streaming Devices",
    "TV Wall Mounts",
    "Set-Top Boxes",
    "Remote Controls",
    "Mini Projectors",
    "Blu-ray Players",
    "AV Receivers",
    "Projector Screens",
    "Media Players",
    "Speakers",
    "Gaming Consoles for TV",
    "HDMI Cables",
    "Power Cords",
    "Universal Remotes",
    "TV Accessories"
  ],

  "Kitchen Appliances": [
    "Microwave Ovens",
    "Electric Kettles",
    "Toasters & Sandwich Makers",
    "Coffee Makers",
    "Rice Cookers",
    "Juicers & Blenders",
    "Induction Cooktops",
    "Refrigerators",
    "Dishwashers",
    "Food Processors",
    "Slow Cookers",
    "Electric Grills",
    "Water Purifiers",
    "Choppers",
    "Bread Makers",
    "Ice Cream Makers",
    "Pressure Cookers",
    "Ovens",
    "Popcorn Makers",
    "Food Steamers"
  ],

  "Power Tools": [
    "Drills & Drivers",
    "Angle Grinders",
    "Circular Saws",
    "Welding Machines",
    "Heat Guns",
    "Sanders & Polishers",
    "Electric Screwdrivers",
    "Cutting Machines",
    "Air Compressors",
    "Power Tool Accessories",
    "Hammer Drills",
    "Rotary Tools",
    "Bench Grinders",
    "Cordless Tools",
    "Screwdriver Sets",
    "Impact Wrenches",
    "Tool Kits",
    "Jigsaws",
    "Nail Guns",
    "Tile Cutters"
  ],

  "Hardware & Construction": [
    "Hand Tools",
    "Fasteners",
    "Plumbing Supplies",
    "Safety Gear",
    "Measuring Tools",
    "Paint & Coatings",
    "Adhesives & Sealants",
    "Door & Window Hardware",
    "Construction Materials",
    "Gardening Tools",
    "Power Saws",
    "Tool Storage",
    "Ladders & Scaffolding",
    "Electrical Hardware",
    "Building Materials",
    "Locks & Keys",
    "Concrete Tools",
    "Workshop Tools",
    "Hardware Accessories",
    "Workbenches"
  ],

  "Lighting & Electrical": [
    "LED Bulbs",
    "Tube Lights",
    "Ceiling Lights",
    "Chandeliers",
    "Decorative String Lights",
    "Wall Lamps",
    "Switches & Sockets",
    "Extension Boards",
    "Solar Lights",
    "Emergency Lights",
    "Desk Lamps",
    "Flood Lights",
    "Outdoor Lighting",
    "Smart Lights",
    "Track Lighting",
    "Pendant Lights",
    "Recessed Lighting",
    "Night Lights",
    "Stage Lighting",
    "Industrial Lighting"
  ],

  "Cables & Wires": [
    "HDMI Cables",
    "USB Cables",
    "Power Cords",
    "Ethernet Cables",
    "Audio Cables",
    "Charging Cables",
    "Coaxial Cables",
    "Fiber Optic Cables",
    "Cable Organizers",
    "Industrial Wires",
    "AV Cables",
    "Lightning Cables",
    "Type-C Cables",
    "Extension Cords",
    "Speaker Wires",
    "Network Cables",
    "Monitor Cables",
    "Adapter Cables",
    "Ribbon Cables",
    "Flat Cables"
  ],

  "Gaming & Consoles": [
    "PlayStation Consoles",
    "Xbox Consoles",
    "Nintendo Switch",
    "Gaming PCs",
    "Gaming Controllers",
    "Gaming Keyboards & Mice",
    "Gaming Chairs",
    "Game Discs & Digital Codes",
    "Streaming Gear",
    "VR Gaming Accessories",
    "Arcade Machines",
    "Game Capture Cards",
    "Racing Wheels",
    "Flight Sim Controllers",
    "Gaming Headsets",
    "Gaming Desks",
    "Graphics Cards for Gaming",
    "Cooling Fans for Gaming PCs",
    "LED Gaming Lights",
    "Gamepads & Joysticks"
  ]
} as const;

export type ParentCategoryName = keyof typeof parentToSubCategories;
export type SubCategoryName = typeof parentToSubCategories[ParentCategoryName][number];




export const allBrands = {
  "Smartphones & Tablets": [
    "Samsung",
    "Apple",
    "OnePlus",
    "Xiaomi",
    "Vivo",
    "Oppo",
    "Realme",
    "Huawei",
    "Nokia",
    "Google Pixel",
    "Motorola",
    "Sony",
    "LG",
    "Asus",
    "Lenovo",
    "Tecno",
    "Infinix",
    "Redmi",
    "BlackBerry",
    "Honor",
  ],
  "Feature Phones": [
    "Nokia",
    "Samsung",
    "Itel",
    "Lava",
    "Karbonn",
    "Micromax",
    "Panasonic",
    "Alcatel",
    "Gionee",
    "Intex",
    "Walton",
    "Symphony",
    "Tecno",
    "Fly",
    "Xolo",
    "iBall",
    "Prestigio",
    "ZTE",
    "Sony Ericsson",
    "LG",
  ],
  "Monitors & Displays": [
    "Dell",
    "HP",
    "Samsung",
    "LG",
    "Asus",
    "Acer",
    "BenQ",
    "ViewSonic",
    "MSI",
    "Apple",
    "Lenovo",
    "Philips",
    "Gigabyte",
    "Eizo",
    "Panasonic",
    "NEC",
    "HP Omen",
    "Alienware",
    "Sceptre",
    "Sharp",
  ],
  "Cameras & Photography": [
    "Canon",
    "Nikon",
    "Sony",
    "Fujifilm",
    "Panasonic",
    "Olympus",
    "Leica",
    "Pentax",
    "GoPro",
    "Kodak",
    "Ricoh",
    "Sigma",
    "Tamron",
    "Hasselblad",
    "DJI",
    "Blackmagic",
    "YI",
    "Insta360",
    "Polaroid",
    "Minolta",
  ],
  "DSLRs & Mirrorless Cameras": [
    "Canon",
    "Nikon",
    "Sony",
    "Fujifilm",
    "Panasonic",
    "Olympus",
    "Leica",
    "Pentax",
    "Sigma",
    "Tamron",
    "Samsung",
    "Kodak",
    "Hasselblad",
    "GoPro",
    "DJI",
    "Blackmagic",
    "YI",
    "Insta360",
    "Ricoh",
    "Minolta",
  ],
  "Drones & Action Cameras": [
    "DJI",
    "GoPro",
    "Parrot",
    "Yuneec",
    "Autel",
    "Hubsan",
    "Syma",
    "Holy Stone",
    "Potensic",
    "Xiaomi",
    "Ruko",
    "Snaptain",
    "Eachine",
    "Ryze",
    "Walkera",
    "Happymodel",
    "FPV Factory",
    "Tello",
    "LeEco",
    "SJCAM",
  ],
  "Wearables & Smartwatches": [
    "Apple",
    "Samsung",
    "Fitbit",
    "Garmin",
    "Huawei",
    "Amazfit",
    "Fossil",
    "TicWatch",
    "Suunto",
    "Withings",
    "Skagen",
    "Michael Kors",
    "Polar",
    "Honor",
    "Xiaomi",
    "Mobvoi",
    "Noise",
    "Realme",
    "Oppo",
    "OnePlus",
  ],
  "Audio Devices": [
    "Bose",
    "Sony",
    "JBL",
    "Sennheiser",
    "Beats",
    "Audio-Technica",
    "Bang & Olufsen",
    "Skullcandy",
    "Philips",
    "AKG",
    "Harman Kardon",
    "Marshall",
    "Logitech",
    "Razer",
    "Creative",
    "Plantronics",
    "Focal",
    "Shure",
    "Fender",
    "Edifier",
  ],
  "Home Audio Systems": [
    "Bose",
    "Sony",
    "Samsung",
    "LG",
    "JBL",
    "Yamaha",
    "Denon",
    "Onkyo",
    "Pioneer",
    "Harman Kardon",
    "Marshall",
    "Bang & Olufsen",
    "Klipsch",
    "Polk Audio",
    "Philips",
    "Panasonic",
    "TCL",
    "F&D",
    "Sharp",
    "Creative",
  ],
  "Projectors & Accessories": [
    "Epson",
    "BenQ",
    "Optoma",
    "ViewSonic",
    "LG",
    "Sony",
    "Acer",
    "Panasonic",
    "Xiaomi",
    "Vankyo",
    "Anker",
    "Nebula",
    "Kodak",
    "Vivibright",
    "Artlii",
    "Goodee",
    "Optomax",
    "Jinhoo",
    "YABER",
    "AUN",
  ],
  "VR Headsets & Gaming Gear": [
    "Oculus",
    "HTC Vive",
    "PlayStation VR",
    "Valve Index",
    "Pimax",
    "Samsung",
    "Lenovo",
    "HP",
    "Microsoft",
    "Google",
    "DPVR",
    "Merge VR",
    "Xiaomi",
    "Sony",
    "Insomniac",
    "Razer",
    "HP Reverb",
    "HTC",
    "Samsung Odyssey",
    "Kandao",
  ],
  "E-Readers & Tablets": [
    "Amazon Kindle",
    "Kobo",
    "Barnes & Noble",
    "Sony",
    "PocketBook",
    "Onyx",
    "Samsung",
    "Apple",
    "Lenovo",
    "Huawei",
    "Nook",
    "Tolino",
    "Brydge",
    "Teclast",
    "Chuwi",
    "Vankyo",
    "Alldocube",
    "Xiaomi",
    "Huawei MatePad",
    "Fire HD",
  ],
  "Car Electronics": [
    "Pioneer",
    "Kenwood",
    "Sony",
    "JVC",
    "Alpine",
    "Clarion",
    "Boss Audio",
    "Rockford Fosgate",
    "Infinity",
    "Polk Audio",
    "Kicker",
    "JBL",
    "Panasonic",
    "BOSS",
    "BOSS Car Audio",
    "Boss Audio Systems",
    "Sony Xplod",
    "Pioneer AVH",
    "Kenwood Excelon",
    "Alpine IVA",
  ],
  "Smart Home Devices": [
    "Philips Hue",
    "Google Nest",
    "Amazon Echo",
    "Ring",
    "TP-Link",
    "Xiaomi",
    "Samsung SmartThings",
    "Arlo",
    "Belkin",
    "Honeywell",
    "Logitech",
    "August",
    "iRobot",
    "Ecobee",
    "Wyze",
    "Eufy",
    "Nanoleaf",
    "Netatmo",
    "Leviton",
    "Fibaro",
  ],
  "Networking Devices": [
    "TP-Link",
    "D-Link",
    "Netgear",
    "Asus",
    "Cisco",
    "Ubiquiti",
    "Linksys",
    "Huawei",
    "MikroTik",
    "Tenda",
    "Zyxel",
    "Xiaomi",
    "Belkin",
    "Synology",
    "TRENDnet",
    "Buffalo",
    "Apple",
    "Google Wifi",
    "Orbi",
    "Archer",
  ],
  "Calculators & Electronic Gadgets": [
    "Casio",
    "Texas Instruments",
    "Sharp",
    "Canon",
    "HP",
    "Citizen",
    "Victor",
    "Canon F-715SG",
    "Panasonic",
    "Canon P23-DHV",
    "Mathway",
    "HP Prime",
    "TI-84",
    "TI-89",
    "Canon LS-82Z",
    "Casio fx-991EX",
    "Canon LS-100",
    "Canon LS-2700",
    "HP 12C",
    "Canon P25-DHV",
  ],
  "Office Electronics": [
    "Canon",
    "HP",
    "Brother",
    "Epson",
    "Samsung",
    "Dell",
    "Lexmark",
    "Ricoh",
    "Panasonic",
    "Sharp",
    "Kyocera",
    "Oki",
    "Konica Minolta",
    "Fujitsu",
    "Apple",
    "Lenovo",
    "Canon LBP",
    "HP LaserJet",
    "Brother HL",
    "Samsung Xpress",
  ],
  "Walkie Talkies & Communication Devices": [
    "Motorola",
    "Kenwood",
    "Baofeng",
    "Midland",
    "Icom",
    "Hytera",
    "Yaesu",
    "Uniden",
    "Cobra",
    "Retevis",
    "Vertex Standard",
    "Alinco",
    "Wouxun",
    "BaoFeng UV-5R",
    "Motorola T600",
    "Kenwood TK-3401",
    "Icom IC-V86",
    "Yaesu FT-60R",
    "Midland GXT1000VP4",
    "Cobra ACXT1035",
  ],
  "Portable Media Players": [
    "Apple iPod",
    "Sony Walkman",
    "SanDisk Sansa",
    "Cowon",
    "Fiio",
    "Microsoft Zune",
    "Creative Zen",
    "Sony NW-A105",
    "iBasso",
    "Hidizs",
    "Astell&Kern",
    "Onkyo",
    "AGPTEK",
    "Shanling",
    "Pioneer XDP",
    "FiiO M9",
    "Sony NW-ZX507",
    "Cowon Plenue",
    "Apple iPod Touch",
    "SanDisk Clip Sport",
  ],
  "Headphones & Speakers": [
    "Sony",
    "Bose",
    "JBL",
    "Sennheiser",
    "Beats",
    "Audio-Technica",
    "Bang & Olufsen",
    "Skullcandy",
    "Philips",
    "Marshall",
    "AKG",
    "Logitech",
    "Razer",
    "Creative",
    "Focal",
    "Shure",
    "JVC",
    "Panasonic",
    "Harman Kardon",
    "Plantronics",
  ],

  //next

  "Phone Cases & Covers": [
    "Spigen",
    "OtterBox",
    "Ringke",
    "UAG",
    "Caseology",
    "ESR",
    "Anccer",
    "Skech",
    "Nillkin",
    "Torras",
    "Tech21",
    "i-Blason",
    "Supcase",
    "Mujjo",
    "RhinoShield",
    "Benks",
    "Case-Mate",
    "TORRAS",
    "Dux Ducis",
    "Yoobao",
  ],
  "Screen Protectors": [
    "ZAGG",
    "Spigen",
    "amFilm",
    "ESR",
    "Supershieldz",
    "JETech",
    "OMOTON",
    "LK",
    "IVSO",
    "Tech Armor",
    "Ailun",
    "JETech Premium",
    "Syncwire",
    "QHOHQ",
    "BROTECT",
    "TORRAS",
    "Whitestone",
    "Maxboost",
    "Caseology",
    "ArmorSuit",
  ],
  "Chargers & Power Adapters": [
    "Anker",
    "Aukey",
    "RAVPower",
    "Belkin",
    "Samsung",
    "Apple",
    "UGREEN",
    "CHOETECH",
    "Baseus",
    "Spigen",
    "Zendure",
    "Tronsmart",
    "Romoss",
    "iWALK",
    "Mophie",
    "Xiaomi",
    "OnePlus",
    "Realme",
    "Huawei",
    "OPPO",
  ],
  "Power Banks": [
    "Anker",
    "Xiaomi",
    "RAVPower",
    "Romoss",
    "Aukey",
    "Baseus",
    "UGREEN",
    "Mi",
    "Realme",
    "OPPO",
    "Samsung",
    "Tronsmart",
    "iMuto",
    "Yoobao",
    "Zendure",
    "Poweradd",
    "EasyAcc",
    "Mophie",
    "Jackery",
    "Pisen",
  ],
  "Earphones & Headphones": [
    "Sony",
    "Bose",
    "JBL",
    "Sennheiser",
    "Beats",
    "Skullcandy",
    "Audio-Technica",
    "Bang & Olufsen",
    "Philips",
    "AKG",
    "Marshall",
    "Logitech",
    "Razer",
    "Creative",
    "Focal",
    "Shure",
    "Plantronics",
    "Xiaomi",
    "Realme",
    "OnePlus",
  ],
  "Bluetooth Speakers": [
    "JBL",
    "Bose",
    "Sony",
    "Anker",
    "UE",
    "Marshall",
    "Creative",
    "Harman Kardon",
    "Philips",
    "LG",
    "Tronsmart",
    "iHome",
    "Doss",
    "Fugoo",
    "TaoTronics",
    "Altec Lansing",
    "Xiaomi",
    "Boat",
    "Zebronics",
    "Skullcandy",
  ],
  "Car Mounts & Holders": [
    "iOttie",
    "Spigen",
    "Mpow",
    "AUKEY",
    "VAVA",
    "Baseus",
    "Belkin",
    "WizGear",
    "Kenu",
    "Scosche",
    "Anker",
    "TORRAS",
    "Ringke",
    "ESR",
    "Pitaka",
    "Choetech",
    "Nite Ize",
    "GUB",
    "Olixar",
    "Lamicall",
  ],
  "USB Cables & Connectors": [
    "Anker",
    "UGREEN",
    "Aukey",
    "Baseus",
    "Apple",
    "Samsung",
    "CHOETECH",
    "Tronsmart",
    "Spigen",
    "Belkin",
    "RAVPower",
    "Syncwire",
    "iXCC",
    "CableCreation",
    "AmazonBasics",
    "TORRAS",
    "Yoobao",
    "Mophie",
    "JSAUX",
    "Satechi",
  ],
  "Selfie Sticks & Tripods": [
    "Manfrotto",
    "JOBY",
    "UBeesize",
    "Aukey",
    "Anker",
    "Xiaomi",
    "BlitzWolf",
    "Spigen",
    "Neewer",
    "Fotopro",
    "PULUZ",
    "Yunteng",
    "Velbon",
    "Benro",
    "CamKix",
    "Mpow",
    "GoPro",
    "Fugetek",
    "Smartwe",
    "QZSD",
  ],
  "Smartwatch Bands": [
    "Apple",
    "Spigen",
    "Supcase",
    "Carterjett",
    "Fullmosa",
    "WFEAGL",
    "Barton Bands",
    "Nomad",
    "UAG",
    "Marge Plus",
    "OULUOQI",
    "MoKo",
    "Bobo Bird",
    "Samsung",
    "Fitbit",
    "Garmin",
    "Huawei",
    "Xiaomi",
    "Realme",
    "Noise",
  ],
  "Wireless Charging Pads": [
    "Anker",
    "Belkin",
    "Samsung",
    "CHOETECH",
    "Mophie",
    "Spigen",
    "Yootech",
    "RAVPower",
    "Native Union",
    "Seneo",
    "Tronsmart",
    "UGREEN",
    "Baseus",
    "iOttie",
    "TORRAS",
    "Elecjet",
    "ESR",
    "Poweradd",
    "OnePlus",
    "Xiaomi",
  ],
  "Phone Camera Lenses": [
    "Apexel",
    "Xenvo",
    "Moment",
    "CamKix",
    "OLYMPUS",
    "DJI",
    "Sandmarc",
    "Peachor",
    "ShiftCam",
    "Ailun",
    "Pergear",
    "Hama",
    "Pixco",
    "SmartDevil",
    "KingMa",
    "Sunpak",
    "Ulanzi",
    "Meike",
    "Ztylus",
    "Viltrox",
  ],
  "Phone Stands & Holders": [
    "Lamicall",
    "Anker",
    "UGREEN",
    "Nulaxy",
    "OMOTON",
    "UBeesize",
    "Tryone",
    "Spigen",
    "TORRAS",
    "HDE",
    "Yoobao",
    "Adjustable Stand",
    "BlitzWolf",
    "Mpow",
    "Baseus",
    "AmazonBasics",
    "Belkin",
    "Samsung",
    "Xiaomi",
    "Apple",
  ],
  "Gaming Controllers for Mobiles": [
    "Razer",
    "GameSir",
    "8BitDo",
    "SteelSeries",
    "Flydigi",
    "MOGA",
    "PDP",
    "EasySMX",
    "Ipega",
    "Gamesir",
    "PowerA",
    "Horipad",
    "GuliKit",
    "Gamevice",
    "Hori",
    "ControllerGear",
    "Tayogo",
    "Gamesir X2",
    "Brook",
    "Redragon",
  ],
  "Stylus Pens": [
    "Apple",
    "Adonit",
    "Wacom",
    "MEKO",
    "Logitech",
    "XP-Pen",
    "Huion",
    "Staedtler",
    "Fintie",
    "Mixoo",
    "Ciscle",
    "Hahakee",
    "Evach",
    "Anker",
    "Samsung",
    "Lenovo",
    "Microsoft",
    "TeckNet",
    "Baseus",
    "Huawei",
  ],
  "Mobile Cleaning Kits": [
    "iKlear",
    "Whoosh!",
    "Screen Mom",
    "Whoosh",
    "OXO",
    "Tech Armor",
    "Turtle Wax",
    "Zeiss",
    "Eco-Fused",
    "Whoosh Pro",
    "ColorCoral",
    "Eltima",
    "Dust-Off",
    "MagicFiber",
    "Hama",
    "PureClear",
    "Antec",
    "ESR",
    "Moshi",
    "CleanOn",
  ],
  "SIM Card Adapters & Tools": [
    "Orico",
    "StarTech",
    "Nimaso",
    "Omoton",
    "Anker",
    "UGREEN",
    "ESR",
    "Satechi",
    "Apple",
    "Samsung",
    "Baseus",
    "Tronsmart",
    "TORRAS",
    "Yoobao",
    "Mophie",
    "Choetech",
    "Aukey",
    "Spigen",
    "RAVPower",
    "Syncwire",
  ],
  "Portable Phone Fans & Cooling Accessories": [
    "Opolar",
    "Baseus",
    "EasyAcc",
    "Xiaomi",
    "Anker",
    "YOFO",
    "Havit",
    "BlitzWolf",
    "RavPower",
    "KLOUDI",
    "USBfan",
    "TORRAS",
    "Mifan",
    "Tronsmart",
    "UGREEN",
    "CHOETECH",
    "Yoobao",
    "CoolCold",
    "TeckNet",
    "Zacro",
  ],
  "Phone Wallets & Pouches": [
    "Spigen",
    "Bellroy",
    "Nomad",
    "OtterBox",
    "Caseology",
    "TORRAS",
    "ESR",
    "Sena",
    "Pad & Quill",
    "Harber London",
    "Mujjo",
    "UAG",
    "Noreve",
    "dbramante1928",
    "Vaja",
    "Torras",
    "MoKo",
    "Yoobao",
    "Anccer",
    "Torras",
  ],
  "VR Headsets for Mobile": [
    "Samsung Gear VR",
    "Google Daydream",
    "Merge VR",
    "Pansonite",
    "DESTEK",
    "VR Shinecon",
    "Homido",
    "BlitzWolf",
    "Bnext",
    "BoboVR",
    "Ant VR",
    "Deepoon",
    "Kingdom VR",
    "VR Box",
    "Pimax",
    "VR Shinecon 2",
    "Anccer",
    "Cmoar",
    "VR Master",
    "CooSpo",
  ],
  "Gaming Laptops": [
    "Alienware",
    "Asus ROG",
    "MSI",
    "Acer Predator",
    "Lenovo Legion",
    "HP Omen",
    "Dell G Series",
    "Gigabyte Aorus",
    "Razer Blade",
    "Samsung Odyssey",
    "ASUS TUF",
    "MSI Stealth",
    "HP Pavilion Gaming",
    "Acer Nitro",
    "Dell Inspiron Gaming",
    "Lenovo IdeaPad Gaming",
    "MSI GE Series",
    "Gigabyte Aero",
    "Razer Blade Stealth",
    "HP Victus",
  ],
  "Business Laptops": [
    "Dell Latitude",
    "Lenovo ThinkPad",
    "HP EliteBook",
    "Microsoft Surface",
    "Apple MacBook Pro",
    "Asus ExpertBook",
    "Acer TravelMate",
    "Samsung Notebook 9",
    "LG Gram",
    "Huawei MateBook",
    "Toshiba Tecra",
    "Fujitsu Lifebook",
    "Panasonic Toughbook",
    "Dell XPS",
    "HP ProBook",
    "Lenovo Yoga",
    "Asus ZenBook",
    "MSI Modern",
    "Razer Book",
    "Samsung Galaxy Book",
  ],
  Laptops: [
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "MSI",
    "Apple",
    "Samsung",
    "Huawei",
    "LG",
    "Razer",
    "Microsoft",
    "Gigabyte",
    "Fujitsu",
    "Toshiba",
    "Panasonic",
    "Chuwi",
    "Dynabook",
    "Teclast",
    "Realme",
  ],
  "Desktop PCs": [
    "Dell",
    "HP",
    "Lenovo",
    "Acer",
    "Asus",
    "MSI",
    "Apple iMac",
    "CyberPowerPC",
    "iBUYPOWER",
    "Corsair",
    "NZXT",
    "Razer",
    "Origin PC",
    "Falcon Northwest",
    "Maingear",
    "Alienware",
    "Gigabyte",
    "Intel NUC",
    "Beelink",
    "MinisForum",
  ],
  Desktops: [
    "Dell Inspiron",
    "HP Pavilion",
    "Lenovo IdeaCentre",
    "Asus VivoPC",
    "Acer Aspire",
    "MSI Cubi",
    "Apple iMac",
    "Corsair One",
    "Intel NUC",
    "Gigabyte Brix",
    "Beelink",
    "HP EliteDesk",
    "Dell OptiPlex",
    "Lenovo ThinkCentre",
    "Asus Mini PC",
    "Zotac Zbox",
    "MSI Pro",
    "Acer Veriton",
    "Raspberry Pi",
    "Intel Compute Stick",
  ],
  Monitors: [
    "Dell",
    "Asus",
    "LG",
    "Samsung",
    "Acer",
    "BenQ",
    "MSI",
    "HP",
    "ViewSonic",
    "Philips",
    "Gigabyte",
    "Apple",
    "Lenovo",
    "AOC",
    "Xiaomi",
    "Alienware",
    "Razer",
    "Eizo",
    "NEC",
    "Sharp",
  ],
  "Keyboards & Mice": [
    "Logitech",
    "Razer",
    "Corsair",
    "SteelSeries",
    "HyperX",
    "Asus",
    "MSI",
    "HP",
    "Dell",
    "Apple",
    "Microsoft",
    "Cooler Master",
    "Redragon",
    "Acer",
    "Lenovo",
    "Gigabyte",
    "Thermaltake",
    "Zowie",
    "Roccat",
    "Ducky",
  ],
  "RAM & Graphics Cards": [
    "Corsair",
    "G.Skill",
    "Kingston",
    "Crucial",
    "ADATA",
    "Patriot",
    "Samsung",
    "HyperX",
    "PNY",
    "EVGA",
    "MSI",
    "Asus",
    "Gigabyte",
    "Zotac",
    "Sapphire",
    "XFX",
    "PowerColor",
    "Palit",
    "Inno3D",
    "PNY XLR8",
  ],
  "External Hard Drives & SSD": [
    "Seagate",
    "Western Digital",
    "Samsung",
    "SanDisk",
    "Crucial",
    "ADATA",
    "Kingston",
    "LaCie",
    "Toshiba",
    "Transcend",
    "WD_BLACK",
    "PNY",
    "G-Technology",
    "Lexar",
    "Intenso",
    "Buffalo",
    "HGST",
    "Orico",
    "iStorage",
    "Sabrent",
  ],
  "UPS & Power Solutions": [
    "APC",
    "CyberPower",
    "Eaton",
    "Tripp Lite",
    "Vertiv",
    "Liebert",
    "Emerson",
    "PowerWalker",
    "Riello",
    "Delta",
    "Exide",
    "Luminous",
    "Microtek",
    "Schneider Electric",
    "Infosec",
    "Numeric",
    "Gamatronic",
    "Must",
    "Legrand",
    "V-Guard",
  ],
  "Docking Stations": [
    "Dell",
    "HP",
    "Lenovo",
    "Kensington",
    "Plugable",
    "Anker",
    "CalDigit",
    "Targus",
    "Belkin",
    "StarTech",
    "OWC",
    "Satechi",
    "Lenovo ThinkPad",
    "Dell Thunderbolt",
    "Microsoft",
    "Kensington SD",
    "HyperDrive",
    "HP EliteDock",
    "Elgato",
    "IOGEAR",
  ],
  "Cooling Pads": [
    "Cooler Master",
    "Thermaltake",
    "DeepCool",
    "HAVIT",
    "Klim",
    "TopMate",
    "Targus",
    "AICHESON",
    "TECKNET",
    "Acousta",
    "KLIM Cyclone",
    "Havit HV-F2056",
    "TopMate C5",
    "Trust GXT",
    "Klim Wind",
    "Zalman",
    "Evercool",
    "iFans",
    "Jonsbo",
    "Nubwo",
  ],
  Motherboards: [
    "Asus",
    "MSI",
    "Gigabyte",
    "ASRock",
    "EVGA",
    "Biostar",
    "Intel",
    "Supermicro",
    "DFI",
    "Foxconn",
    "MSI MEG",
    "Gigabyte AORUS",
    "Asus ROG",
    "AsRock Phantom",
    "EVGA Classified",
    "SuperO",
    "Biostar Racing",
    "Intel DZ",
    "TUF Gaming",
    "ROG Strix",
  ],
  Processors: [
    "Intel",
    "AMD",
    "Apple M1",
    "Apple M2",
    "Qualcomm Snapdragon",
    "MediaTek",
    "Samsung Exynos",
    "VIA",
    "Zhaoxin",
    "IBM Power",
    "Intel Core",
    "AMD Ryzen",
    "Intel Xeon",
    "AMD EPYC",
    "Apple M1 Pro",
    "Apple M1 Max",
    "Apple M2 Pro",
    "Apple M2 Max",
    "Intel Pentium",
    "Intel Celeron",
  ],
  "GPU & Graphics Cards": [
    "NVIDIA",
    "AMD",
    "Intel",
    "Asus",
    "MSI",
    "Gigabyte",
    "EVGA",
    "Sapphire",
    "Zotac",
    "PowerColor",
    "PNY",
    "XFX",
    "Palit",
    "Gainward",
    "Colorful",
    "MSI Gaming",
    "Gigabyte AORUS",
    "ASRock Phantom",
    "ASUS TUF",
    "Inno3D",
  ],
  "Laptop Bags & Sleeves": [
    "Samsonite",
    "Targus",
    "Case Logic",
    "Lenovo",
    "HP",
    "Dell",
    "KROSER",
    "MOSISO",
    "Inateck",
    "AmazonBasics",
    "Tomtoc",
    "Thule",
    "SwissGear",
    "STM",
    "Booq",
    "Lacdo",
    "Everki",
    "Solo",
    "Tucano",
    "UAG",
  ],
  "Laptop Stands": [
    "Rain Design",
    "Nulaxy",
    "Twelve South",
    "MOFT",
    "Roost",
    "AmazonBasics",
    "Lamicall",
    "Kensington",
    "Besign",
    "iQunix",
    "Anker",
    "Jelly Comb",
    "UGREEN",
    "ORICO",
    "Baseus",
    "Bluelounge",
    "Cooler Master",
    "DeepCool",
    "Vivo",
    "Havit",
  ],
  "Networking Cards & Adapters": [
    "TP-Link",
    "Netgear",
    "Asus",
    "D-Link",
    "Intel",
    "Killer",
    "Linksys",
    "Rosewill",
    "Edimax",
    "TRENDnet",
    "Ubiquiti",
    "Belkin",
    "Realtek",
    "Logitech",
    "MikroTik",
    "Cisco",
    "Buffalo",
    "HPE",
    "Tenda",
    "ZYXEL",
  ],
  Printers: [
    "HP",
    "Canon",
    "Epson",
    "Brother",
    "Lexmark",
    "Samsung",
    "Dell",
    "Xerox",
    "Ricoh",
    "Pantum",
    "OKI",
    "Kyocera",
    "Sharp",
    "Konica Minolta",
    "Toshiba",
    "Epson WorkForce",
    "HP LaserJet",
    "Canon Pixma",
    "Brother DCP",
    "Epson EcoTank",
  ],
  Scanners: [
    "Fujitsu",
    "Canon",
    "Epson",
    "Brother",
    "Plustek",
    "Kodak",
    "HP",
    "Microtek",
    "Visioneer",
    "IRIS",
    "Avision",
    "Mustek",
    "Xerox",
    "Panasonic",
    "Dell",
    "Ricoh",
    "ScanSnap",
    "PFU",
    "EPSON Perfection",
    "Acer",
  ],
  "LED TVs": [
    "Samsung",
    "LG",
    "Sony",
    "Panasonic",
    "TCL",
    "Hisense",
    "Vizio",
    "Philips",
    "Sharp",
    "Toshiba",
    "Insignia",
    "Sceptre",
    "Haier",
    "Bang & Olufsen",
    "Thomson",
    "Akai",
    "Skyworth",
    "Changhong",
    "Element",
    "JVC",
  ],
  "Smart TVs": [
    "Samsung",
    "LG",
    "Sony",
    "Panasonic",
    "TCL",
    "Hisense",
    "Vizio",
    "Philips",
    "Toshiba",
    "Sharp",
    "Insignia",
    "Skyworth",
    "Changhong",
    "Xiaomi",
    "OnePlus",
    "Realme",
    "Kodak",
    "Hitachi",
    "Haier",
    "Westinghouse",
  ],
  "4K & OLED TVs": [
    "LG",
    "Sony",
    "Samsung",
    "Panasonic",
    "Vizio",
    "TCL",
    "Philips",
    "Hisense",
    "Sharp",
    "Panasonic OLED",
    "LG CX",
    "LG GX",
    "Sony Bravia",
    "Samsung QLED",
    "TCL 6-Series",
    "Vizio P-Series",
    "Philips Ambilight",
    "Panasonic GZ",
    "Sony A9",
    "LG C1",
  ],
  "Home Theater Systems": [
    "Bose",
    "Sony",
    "Samsung",
    "LG",
    "Yamaha",
    "Panasonic",
    "Onkyo",
    "Denon",
    "Pioneer",
    "Harman Kardon",
    "Klipsch",
    "Polk Audio",
    "JBL",
    "Philips",
    "Sharp",
    "Focal",
    "Cambridge Audio",
    "Marantz",
    "Teufel",
    "Definitive Technology",
  ],
  Soundbars: [
    "Samsung",
    "LG",
    "Sony",
    "Bose",
    "JBL",
    "Yamaha",
    "Sonos",
    "Vizio",
    "Polk Audio",
    "Denon",
    "Klipsch",
    "Philips",
    "Panasonic",
    "Sharp",
    "Sennheiser",
    "Bang & Olufsen",
    "Onkyo",
    "Focal",
    "Harman Kardon",
    "TCL",
  ],
  "Streaming Devices": [
    "Roku",
    "Amazon Fire TV",
    "Apple TV",
    "Google Chromecast",
    "NVIDIA Shield",
    "Xiaomi Mi Box",
    "Samsung Smart Hub",
    "LG WebOS",
    "Sony Bravia TV",
    "TCL Roku TV",
    "Philips Android TV",
    "Panasonic Smart TV",
    "Hisense Roku TV",
    "Vizio SmartCast",
    "OnePlus TV",
    "Realme Smart TV",
    "Mi TV Stick",
    "Skyworth Android TV",
    "Sharp Smart TV",
    "Haier Smart TV",
  ],
  "TV Wall Mounts": [
    "Sanus",
    "ECHOGEAR",
    "VideoSecu",
    "Mounting Dream",
    "Vogel's",
    "PERLESMITH",
    "Peerless",
    "OmniMount",
    "Rocketfish",
    "HIDEit Mounts",
    "Cheetah Mounts",
    "Loctek",
    "Mounting Essentials",
    "Acer Mounts",
    "Sony Bravia Mounts",
    "LG Wall Mount",
    "Samsung Wall Mount",
    "Sharp Wall Mount",
    "Philips Wall Mount",
    "TCL Wall Mount",
  ],
  "Set-Top Boxes": [
    "Apple TV",
    "Roku",
    "Amazon Fire TV",
    "Google Chromecast",
    "NVIDIA Shield",
    "Sky Q",
    "Dish Network",
    "Xfinity X1",
    "Tivo",
    "Huawei MediaBox",
    "MAG",
    "Formuler",
    "Infomir",
    "Dreamlink",
    "BuzzTV",
    "Amiko",
    "Zgemma",
    "Beelink",
    "Tanix",
    "Vankyo",
  ],
  "Remote Controls": [
    "Logitech",
    "Inteset",
    "GE",
    "Sony",
    "Samsung",
    "LG",
    "Philips",
    "Roku",
    "Amazon Fire",
    "Apple TV",
    "Sideclick",
    "Fintie",
    "One For All",
    "RaySuper",
    "Caavo",
    "PDP",
    "HUAYI",
    "Nevo",
    "URC",
    "XRT",
  ],
  "Mini Projectors": [
    "Anker Nebula",
    "ViewSonic",
    "Epson",
    "BenQ",
    "LG",
    "Optoma",
    "XGIMI",
    "Vankyo",
    "Kodak",
    "AAXA",
    "Apeman",
    "Vivitek",
    "RCA",
    "Crenova",
    "GoVision",
    "BlitzWolf",
    "Artlii",
    "Fangor",
    "PIQS",
    "Elephas",
  ],
  "Blu-ray Players": [
    "Sony",
    "Panasonic",
    "LG",
    "Samsung",
    "Pioneer",
    "Philips",
    "Denon",
    "Sharp",
    "Yamaha",
    "Onkyo",
    "JVC",
    "Hitachi",
    "Toshiba",
    "Funai",
    "Magnavox",
    "Marantz",
    "CyberHome",
    "Acer",
    "Sylvania",
    "Fujitsu",
  ],
  "AV Receivers": [
    "Denon",
    "Yamaha",
    "Onkyo",
    "Marantz",
    "Pioneer",
    "Sony",
    "Samsung",
    "LG",
    "Integra",
    "Harman Kardon",
    "Rotel",
    "Cambridge Audio",
    "Anthem",
    "Klipsch",
    "Arcam",
    "Bowers & Wilkins",
    "Sherwood",
    "Luxman",
    "TEAC",
    "NAD",
  ],
  "Projector Screens": [
    "Elite Screens",
    "Silver Ticket",
    "Vividstorm",
    "Draper",
    "Grandview",
    "ViewSonic",
    "BenQ",
    "Optoma",
    "Epson",
    "JWS",
    "Akia",
    "CineGrey",
    "OmniMount",
    "Homegear",
    "Saker",
    "Celexon",
    "Kikori",
    "Da-Lite",
    "Duronic",
    "Vankyo",
  ],
  "Media Players": [
    "Apple",
    "Roku",
    "Amazon Fire TV",
    "Google Chromecast",
    "NVIDIA Shield",
    "Xiaomi Mi Box",
    "Samsung Smart Hub",
    "LG WebOS",
    "Sony Bravia",
    "Philips Android TV",
    "Panasonic Smart TV",
    "Vizio SmartCast",
    "OnePlus TV",
    "Realme Smart TV",
    "Skyworth Android TV",
    "Sharp Smart TV",
    "Haier Smart TV",
    "TCL Roku TV",
    "BuzzTV",
    "Beelink",
  ],
  Speakers: [
    "Bose",
    "JBL",
    "Sony",
    "Samsung",
    "LG",
    "Yamaha",
    "Klipsch",
    "Harman Kardon",
    "Polk Audio",
    "Bang & Olufsen",
    "Onkyo",
    "Denon",
    "Focal",
    "KEF",
    "Creative",
    "Anker",
    "Marshall",
    "Jamo",
    "Philips",
    "Logitech",
  ],
  "Gaming Consoles for TV": [
    "Sony PlayStation",
    "Microsoft Xbox",
    "Nintendo Switch",
    "Nvidia Shield",
    "Atari VCS",
    "Retro-Bit",
    "OUYA",
    "Sony PlayStation 5",
    "Xbox Series X",
    "Xbox Series S",
    "Nintendo Wii",
    "Nintendo Wii U",
    "Sony PlayStation 4",
    "Xbox One",
    "Nintendo NES Classic",
    "Sega Genesis Mini",
    "Sony PlayStation 3",
    "Xbox 360",
    "Nintendo 64",
    "Sony PS2",
  ],
  "HDMI Cables": [
    "AmazonBasics",
    "Belkin",
    "Cable Matters",
    "Anker",
    "UGREEN",
    "Monoprice",
    "Rankie",
    "Mediabridge",
    "BlueRigger",
    "iVANKY",
    "Syncwire",
    "Rocketfish",
    "StarTech",
    "Accell",
    "Fosmon",
    "J-Tech Digital",
    "Sony",
    "Samsung",
    "LG",
    "Philips",
  ],
  "Power Cords": [
    "Tripp Lite",
    "AmazonBasics",
    "StarTech",
    "C2G",
    "Belkin",
    "CyberPower",
    "APC",
    "Kensington",
    "Monoprice",
    "Anker",
    "Ugreen",
    "Alogic",
    "Digipower",
    "Fosmon",
    "Hosa",
    "Panamax",
    "Furman",
    "KVM",
    "Vanco",
    "Accell",
  ],
  "Universal Remotes": [
    "Logitech",
    "Inteset",
    "GE",
    "RCA",
    "Philips",
    "Sony",
    "Samsung",
    "LG",
    "One For All",
    "RaySuper",
    "Sideclick",
    "Caavo",
    "PDP",
    "Fintie",
    "Nevo",
    "URC",
    "Hama",
    "Huayu",
    "XRT",
    "Pyle",
  ],
  "TV Accessories": [
    "Sanus",
    "ECHOGEAR",
    "OmniMount",
    "Mounting Dream",
    "Rocketfish",
    "Cheetah",
    "PERLESMITH",
    "Loctek",
    "Vogel's",
    "HIDEit",
    "Twelve South",
    "Anker",
    "Philips",
    "Samsung",
    "LG",
    "Sony",
    "Sharp",
    "TCL",
    "Panasonic",
    "Hisense",
  ],

  "Microwave Ovens": [
    "Panasonic",
    "Samsung",
    "LG",
    "Sharp",
    "Bosch",
    "IFB",
    "Whirlpool",
    "Haier",
    "Midea",
    "Toshiba",
    "Electrolux",
    "Bajaj",
    "Kenstar",
    "Morphy Richards",
    "Philips",
    "Arcelik",
    "Hitachi",
    "GE Appliances",
    "Breville",
    "KitchenAid",
  ],
  "Electric Kettles": [
    "Philips",
    "Bajaj",
    "Morphy Richards",
    "Prestige",
    "Hamilton Beach",
    "Black+Decker",
    "Panasonic",
    "Russell Hobbs",
    "Braun",
    "Kenwood",
    "Cuisinart",
    "Bosch",
    "Severin",
    "Tefal",
    "Kitchenaid",
    "Hamilton",
    "RussellH",
    "Aicok",
    "VonShef",
    "Ovente",
  ],
  "Toasters & Sandwich Makers": [
    "Philips",
    "Bajaj",
    "Morphy Richards",
    "Prestige",
    "Black+Decker",
    "Hamilton Beach",
    "Cuisinart",
    "Panasonic",
    "Russell Hobbs",
    "Tefal",
    "Kenwood",
    "Breville",
    "Bosch",
    "Oster",
    "Sencor",
    "Severin",
    "Hamilton",
    "VonShef",
    "Ovente",
    "Aigostar",
  ],
  "Coffee Makers": [
    "Nespresso",
    "DeLonghi",
    "Breville",
    "Krups",
    "Philips",
    "Bajaj",
    "Morphy Richards",
    "Bosch",
    "Cuisinart",
    "Hamilton Beach",
    "Black+Decker",
    "Siemens",
    "Panasonic",
    "Russell Hobbs",
    "Tefal",
    "Kenwood",
    "Oster",
    "Ovente",
    "Sage",
    "Capresso",
  ],
  "Rice Cookers": [
    "Panasonic",
    "Philips",
    "Toshiba",
    "Zojirushi",
    "Cuckoo",
    "Morphy Richards",
    "Bajaj",
    "Kenwood",
    "Tiger",
    "Sencor",
    "Hamilton Beach",
    "Oster",
    "Black+Decker",
    "Russell Hobbs",
    "Severin",
    "Bosch",
    "Prestige",
    "Midea",
    "Arcelik",
    "Ovente",
  ],
  "Juicers & Blenders": [
    "Philips",
    "Bajaj",
    "Panasonic",
    "Braun",
    "Morphy Richards",
    "Kenwood",
    "Hamilton Beach",
    "Black+Decker",
    "Bosch",
    "Russell Hobbs",
    "Tefal",
    "Oster",
    "Severin",
    "Cuisinart",
    "KitchenAid",
    "Sencor",
    "Aicok",
    "NutriBullet",
    "Vitamix",
    "Ovente",
  ],
  "Induction Cooktops": [
    "Prestige",
    "Bajaj",
    "Philips",
    "Pigeon",
    "Morphy Richards",
    "Usha",
    "Butterfly",
    "Kenstar",
    "Inalsa",
    "Panasonic",
    "Havells",
    "Bosch",
    "Kent",
    "Vega",
    "Black+Decker",
    "Hamilton Beach",
    "Usha Kitchen",
    "Cuisinart",
    "Oster",
    "Ovente",
  ],
  Refrigerators: [
    "Samsung",
    "LG",
    "Whirlpool",
    "Godrej",
    "Haier",
    "Panasonic",
    "Bosch",
    "Hitachi",
    "IFB",
    "Midea",
    "Sharp",
    "Electrolux",
    "Beko",
    "Kenstar",
    "Hisense",
    "Toshiba",
    "Arcelik",
    "Haier Thermocool",
    "GE Appliances",
    "Haier India",
  ],
  Dishwashers: [
    "Bosch",
    "LG",
    "Samsung",
    "Whirlpool",
    "IFB",
    "Siemens",
    "KitchenAid",
    "Electrolux",
    "GE Appliances",
    "Miele",
    "Blomberg",
    "Fisher & Paykel",
    "Beko",
    "Frigidaire",
    "Haier",
    "Kenstar",
    "Sharp",
    "Panasonic",
    "Arcelik",
    "Teka",
  ],
  "Food Processors": [
    "Philips",
    "Bosch",
    "Kenwood",
    "Morphy Richards",
    "Cuisinart",
    "Panasonic",
    "Hamilton Beach",
    "Bajaj",
    "Braun",
    "Russell Hobbs",
    "KitchenAid",
    "Oster",
    "Tefal",
    "Severin",
    "Inalsa",
    "Sencor",
    "Aicok",
    "Black+Decker",
    "Ovente",
    "Prestige",
  ],
  "Slow Cookers": [
    "Philips",
    "Prestige",
    "Morphy Richards",
    "Panasonic",
    "Hamilton Beach",
    "Black+Decker",
    "Cuisinart",
    "Russell Hobbs",
    "Oster",
    "Tefal",
    "Kenwood",
    "Braun",
    "Severin",
    "Ovente",
    "Aicok",
    "Bosch",
    "KitchenAid",
    "Sencor",
    "Inalsa",
    "Bajaj",
  ],
  "Electric Grills": [
    "Philips",
    "Prestige",
    "Morphy Richards",
    "Black+Decker",
    "Hamilton Beach",
    "Cuisinart",
    "Kenwood",
    "Oster",
    "Russell Hobbs",
    "Tefal",
    "Severin",
    "Bosch",
    "KitchenAid",
    "Aicok",
    "Ovente",
    "Inalsa",
    "Bajaj",
    "Braun",
    "Sencor",
    "Panasonic",
  ],
  "Water Purifiers": [
    "Kent",
    "Aquaguard",
    "Pureit",
    "Livpure",
    "HUL",
    "Blue Star",
    "AO Smith",
    "Philips",
    "Panasonic",
    "Samsung",
    "LG",
    "AquaSure",
    "Pigeon",
    "Tata Swach",
    "Eureka Forbes",
    "Bajaj",
    "Crompton",
    "Inalsa",
    "Usha",
    "Ovente",
  ],
  Choppers: [
    "Philips",
    "Bajaj",
    "Morphy Richards",
    "Panasonic",
    "Kenwood",
    "Cuisinart",
    "Hamilton Beach",
    "Black+Decker",
    "Braun",
    "Russell Hobbs",
    "Oster",
    "Severin",
    "KitchenAid",
    "Tefal",
    "Inalsa",
    "Aicok",
    "Ovente",
    "Prestige",
    "Sencor",
    "Bosch",
  ],
  "Bread Makers": [
    "Panasonic",
    "Morphy Richards",
    "Philips",
    "Black+Decker",
    "Cuisinart",
    "Kenwood",
    "Russell Hobbs",
    "Oster",
    "Hamilton Beach",
    "Bosch",
    "Tefal",
    "Severin",
    "KitchenAid",
    "Sencor",
    "Aicok",
    "Ovente",
    "Prestige",
    "Inalsa",
    "Bajaj",
    "Braun",
  ],
  "Ice Cream Makers": [
    "Cuisinart",
    "Kenwood",
    "Hamilton Beach",
    "KitchenAid",
    "Morphy Richards",
    "Bajaj",
    "Philips",
    "Russell Hobbs",
    "Oster",
    "Tefal",
    "Severin",
    "Bosch",
    "Aicok",
    "Ovente",
    "Prestige",
    "Inalsa",
    "Braun",
    "Sencor",
    "Panasonic",
    "Black+Decker",
  ],
  "Pressure Cookers": [
    "Prestige",
    "Hawkins",
    "Pigeon",
    "Preethi",
    "Bajaj",
    "Sunflame",
    "Butterfly",
    "Morphy Richards",
    "Panasonic",
    "Philips",
    "Kenwood",
    "Cuisinart",
    "Black+Decker",
    "Inalsa",
    "Usha",
    "Bosch",
    "Severin",
    "Tefal",
    "Hamilton Beach",
    "Ovente",
  ],
  Ovens: [
    "Samsung",
    "LG",
    "Whirlpool",
    "Panasonic",
    "Bosch",
    "Morphy Richards",
    "Prestige",
    "Kenwood",
    "Philips",
    "Oster",
    "Hamilton Beach",
    "Black+Decker",
    "Russell Hobbs",
    "Severin",
    "Tefal",
    "Cuisinart",
    "Aicok",
    "Ovente",
    "KitchenAid",
    "Braun",
  ],
  "Popcorn Makers": [
    "Cuisinart",
    "Nostalgia",
    "Hamilton Beach",
    "West Bend",
    "Presto",
    "Great Northern",
    "Severin",
    "Aicok",
    "Chefman",
    "Elite Cuisine",
    "Kitchenaid",
    "Bestron",
    "Proctor Silex",
    "Starfrit",
    "Ovente",
    "Morphy Richards",
    "Black+Decker",
    "Bajaj",
    "Tefal",
    "Russell Hobbs",
  ],
  "Food Steamers": [
    "Philips",
    "Morphy Richards",
    "Kenwood",
    "Hamilton Beach",
    "Bajaj",
    "Cuisinart",
    "Russell Hobbs",
    "Oster",
    "Black+Decker",
    "Tefal",
    "Severin",
    "Bosch",
    "KitchenAid",
    "Sencor",
    "Aicok",
    "Ovente",
    "Prestige",
    "Panasonic",
    "Inalsa",
    "Braun",
  ],

  // Power Tools
  "Drills & Drivers": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Hitachi",
    "Milwaukee",
    "Ryobi",
    "Metabo",
    "Festool",
    "Einhell",
    "Stanley",
    "Porter-Cable",
    "Kobalt",
    "Craftsman",
    "Hikoki",
    "Skil",
    "AEG",
    "Wolfcraft",
    "TACKLIFE",
    "Dewalt FlexVolt",
  ],
  "Angle Grinders": [
    "Bosch",
    "Makita",
    "DeWalt",
    "Hitachi",
    "Metabo",
    "Black+Decker",
    "Milwaukee",
    "Porter-Cable",
    "Einhell",
    "Skil",
    "Ryobi",
    "Dewalt FlexVolt",
    "Aeg",
    "Craftsman",
    "Worx",
    "Hikoki",
    "TACKLIFE",
    "Ferm",
    "Triton",
  ],
  "Circular Saws": [
    "Makita",
    "DeWalt",
    "Bosch",
    "Hitachi",
    "Milwaukee",
    "Black+Decker",
    "Festool",
    "Porter-Cable",
    "Ryobi",
    "Metabo",
    "Skil",
    "Craftsman",
    "Aeg",
    "TACKLIFE",
    "Ferm",
    "Worx",
    "Hikoki",
    "Einhell",
    "Delta",
    "Evolution",
  ],
  "Welding Machines": [
    "Miller",
    "Lincoln Electric",
    "Hobart",
    "ESAB",
    "Forney",
    "Goplus",
    "YesWelder",
    "Everlast",
    "Lotos",
    "SUNGOLDPOWER",
    "AHP",
    "LOTOS Technology",
    "Chicago Electric",
    "Sealey",
    "Kemppi",
    "Blue Demon",
    "TIG Welder Pro",
    "Vevor",
    "Telwin",
    "Hobart Handler",
  ],
  "Heat Guns": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Wagner",
    "Porter-Cable",
    "Ryobi",
    "Milwaukee",
    "Metabo",
    "Einhell",
    "Craftsman",
    "Skil",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Dewalt FlexVolt",
    "Aeg",
    "Festool",
    "Worx",
    "Stanley",
  ],
  "Sanders & Polishers": [
    "Bosch",
    "Makita",
    "DeWalt",
    "Black+Decker",
    "Festool",
    "Ryobi",
    "Metabo",
    "Milwaukee",
    "Porter-Cable",
    "Skil",
    "Einhell",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "Aeg",
    "Dewalt FlexVolt",
    "Ferm Power",
  ],
  "Electric Screwdrivers": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Ryobi",
    "Milwaukee",
    "Porter-Cable",
    "Skil",
    "Einhell",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Aeg",
    "Craftsman",
    "Festool",
    "Worx",
    "Stanley",
    "Metabo",
    "Dewalt FlexVolt",
    "Ferm Power",
  ],
  "Cutting Machines": [
    "Makita",
    "Bosch",
    "DeWalt",
    "Hitachi",
    "Milwaukee",
    "Black+Decker",
    "Ryobi",
    "Festool",
    "Metabo",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "Aeg",
    "Evolution",
    "Dewalt FlexVolt",
  ],
  "Air Compressors": [
    "DeWalt",
    "Makita",
    "Porter-Cable",
    "California Air Tools",
    "Bostitch",
    "Campbell Hausfeld",
    "Rolair",
    "Metabo",
    "Bosch",
    "Hitachi",
    "Senco",
    "Ryobi",
    "Craftsman",
    "Husky",
    "WEN",
    "Ferm",
    "Ingersoll Rand",
    "Powermate",
    "Fini",
    "Makita MAC2400",
  ],
  "Power Tool Accessories": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Milwaukee",
    "Ryobi",
    "Festool",
    "Metabo",
    "Porter-Cable",
    "Einhell",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "Aeg",
    "Dewalt FlexVolt",
    "Ferm Power",
    "Bosch Accessories",
  ],
  "Hammer Drills": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Hitachi",
    "Milwaukee",
    "Black+Decker",
    "Metabo",
    "Festool",
    "Porter-Cable",
    "Ryobi",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "Aeg",
    "Dewalt FlexVolt",
    "Makita Hammer",
  ],
  "Rotary Tools": [
    "Dremel",
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Proxxon",
    "Ryobi",
    "Milwaukee",
    "Ferm",
    "Einhell",
    "TACKLIFE",
    "Ferm Power",
    "Craftsman",
    "Worx",
    "Skil",
    "Aeg",
    "Dewalt FlexVolt",
    "Hikoki",
    "Metabo",
    "Porter-Cable",
  ],
  "Bench Grinders": [
    "DeWalt",
    "Makita",
    "Bosch",
    "Jet",
    "Grizzly",
    "Metabo",
    "Porter-Cable",
    "Black+Decker",
    "Ryobi",
    "Einhell",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Skil",
    "Aeg",
    "Dewalt FlexVolt",
    "Ferm Power",
    "Jet Bench",
  ],
  "Cordless Tools": [
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Ryobi",
    "Black+Decker",
    "Hitachi",
    "Metabo",
    "Festool",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "Aeg",
    "Dewalt FlexVolt",
    "Bosch Cordless",
  ],
  "Screwdriver Sets": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Ryobi",
    "Milwaukee",
    "Porter-Cable",
    "Skil",
    "Einhell",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Aeg",
    "Craftsman",
    "Festool",
    "Worx",
    "Stanley",
    "Metabo",
    "Dewalt FlexVolt",
    "Bosch Tools",
  ],
  "Impact Wrenches": [
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Ryobi",
    "Hitachi",
    "Metabo",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Black+Decker",
    "AEG",
    "Dewalt FlexVolt",
    "Bosch Impact",
    "Makita Impact",
    "Milwaukee M18",
  ],
  "Tool Kits": [
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Ryobi",
    "Black+Decker",
    "Porter-Cable",
    "Craftsman",
    "Hikoki",
    "Ferm",
    "TACKLIFE",
    "Worx",
    "Skil",
    "AEG",
    "Dewalt FlexVolt",
    "Makita Kit",
    "Bosch Kit",
    "Milwaukee Kit",
    "Hitachi Kit",
    "Metabo Kit",
  ],
  Jigsaws: [
    "Bosch",
    "DeWalt",
    "Makita",
    "Black+Decker",
    "Milwaukee",
    "Ryobi",
    "Metabo",
    "Festool",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Skil",
    "AEG",
    "Porter-Cable",
    "Dewalt FlexVolt",
    "Makita Jigsaw",
    "Bosch Jigsaw",
    "Milwaukee Jigsaw",
  ],
  "Nail Guns": [
    "DeWalt",
    "Paslode",
    "Bostitch",
    "Hitachi",
    "Makita",
    "Metabo",
    "Ryobi",
    "Milwaukee",
    "Bosch",
    "Porter-Cable",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Skil",
    "AEG",
    "Freeman",
    "MAX",
    "Senco",
  ],
  "Tile Cutters": [
    "Rubi",
    "Montolit",
    "Sigma",
    "Sigma Tile",
    "Raimondi",
    "QEP",
    "Husqvarna",
    "Rubi Tools",
    "Sigma 3D",
    "Raimondi Smart",
    "Montolit Masterpiuma",
    "Rubi TX",
    "Sigma Level Plus",
    "Raimondi Speedy",
    "Husqvarna TS",
    "QEP Pro",
    "Rubi TS",
    "Montolit TS",
    "Sigma TS",
    "Raimondi TS",
  ],
  "Hand Tools": [
    "Stanley",
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Ryobi",
    "Craftsman",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Einhell",
    "Ferm",
    "Metabo",
    "Black+Decker",
    "AEG",
    "Porter-Cable",
    "Festool",
    "Skil",
    "Irwin",
    "Klein Tools",
  ],
  Fasteners: [
    "Hilti",
    "Fischer",
    "Spax",
    "Toggler",
    "Red Head",
    "Simpson Strong-Tie",
    "ITW",
    "GRK",
    "Bostitch",
    "Senco",
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Ryobi",
    "Hikoki",
    "Stanley",
    "Craftsman",
    "Fastenal",
    "Hillman",
  ],
  "Plumbing Supplies": [
    "Kohler",
    "Grohe",
    "Moen",
    "Delta",
    "Hansgrohe",
    "Pfister",
    "TOTO",
    "American Standard",
    "Caleffi",
    "Viega",
    "BrassCraft",
    "Watts",
    "Chicago Faucet",
    "Kitz",
    "Roca",
    "Bonomi",
    "Pegler",
    "Hikoki",
    "Niagara",
    "Baldwin",
  ],
  "Safety Gear": [
    "3M",
    "Honeywell",
    "Ansell",
    "MSA",
    "Uvex",
    "Carhartt",
    "Dickies",
    "Ergodyne",
    "Bulwark",
    "Portwest",
    "Lakeland",
    "Kimberly-Clark",
    "Peltor",
    "Moldex",
    "MSA Safety",
    "Black+Decker",
    "DeWalt",
    "Stanley",
    "Bosch",
    "Makita",
  ],
  "Measuring Tools": [
    "Bosch",
    "Stanley",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Hilti",
    "Klein Tools",
    "Stabila",
    "Leica",
    "Pentair",
    "Festool",
    "TACKLIFE",
    "Ferm",
    "Hikoki",
    "AEG",
    "Worx",
    "Skil",
    "Mitutoyo",
    "Komelon",
    "Empire",
  ],
  "Paint & Coatings": [
    "Sherwin-Williams",
    "Benjamin Moore",
    "Asian Paints",
    "Dulux",
    "Behr",
    "Rust-Oleum",
    "Valspar",
    "PPG",
    "Nippon Paint",
    "AkzoNobel",
    "ICI",
    "Jotun",
    "Hempel",
    "Farrow & Ball",
    "Crown Paints",
    "Tiger Drylac",
    "Sikkens",
    "TOA Paint",
    "Kelly-Moore",
    "Glidden",
  ],
  "Adhesives & Sealants": [
    "Loctite",
    "3M",
    "Gorilla",
    "Permatex",
    "Titebond",
    "Bostik",
    "Sika",
    "Henkel",
    "DAP",
    "Elmer's",
    "Everbuild",
    "Araldite",
    "UHU",
    "Mapei",
    "Soudal",
    "Red Devil",
    "Adhesive Technology",
    "Akfix",
    "Techbond",
    "Franklin",
  ],
  "Door & Window Hardware": [
    "Häfele",
    "Assa Abloy",
    "Kwikset",
    "Schlage",
    "Yale",
    "Baldwin",
    "Hettich",
    "Sugatsune",
    "Blum",
    "Roto",
    "Dorma",
    "C.R. Laurence",
    "Stanley",
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Hikoki",
    "TACKLIFE",
    "Worx",
  ],
  "Construction Materials": [
    "Lafarge",
    "Cemex",
    "HeidelbergCement",
    "CRH",
    "Vicat",
    "Saint-Gobain",
    "BASF",
    "Holcim",
    "Sika",
    "Tata Steel",
    "JSW",
    "ArcelorMittal",
    "Boral",
    "James Hardie",
    "Knauf",
    "Hanson",
    "Ash Grove",
    "CalPortland",
    "Lehigh Hanson",
    "Graymont",
  ],
  "Gardening Tools": [
    "Fiskars",
    "Gardena",
    "Husqvarna",
    "Black+Decker",
    "Bosch",
    "Stihl",
    "Makita",
    "Ryobi",
    "DeWalt",
    "Einhell",
    "Troy-Bilt",
    "Worx",
    "Mantis",
    "Toro",
    "Greenworks",
    "Kent & Stowe",
    "Speeco",
    "Corona",
    "Amco",
    "Wolf Garten",
  ],
  "Power Saws": [
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Ryobi",
    "Hitachi",
    "Metabo",
    "Festool",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "AEG",
    "Black+Decker",
    "Dewalt FlexVolt",
    "Makita Saw",
    "Bosch Saw",
  ],
  "Tool Storage": [
    "Stanley",
    "DeWalt",
    "Makita",
    "Bosch",
    "Milwaukee",
    "Husky",
    "Craftsman",
    "Keter",
    "Tactix",
    "Worx",
    "Black+Decker",
    "Porter-Cable",
    "Hikoki",
    "AEG",
    "TACKLIFE",
    "Festool",
    "Skil",
    "Ferm",
    "Kincrome",
    "Beta Tools",
  ],
  "Ladders & Scaffolding": [
    "Werner",
    "Louisville",
    "Little Giant",
    "Cosco",
    "Hailo",
    "Altrex",
    "Krause",
    "Hymer",
    "Gorilla Ladders",
    "DeWalt",
    "Bosch",
    "Makita",
    "Milwaukee",
    "Stanley",
    "Ferm",
    "TACKLIFE",
    "Worx",
    "Hikoki",
    "Black+Decker",
    "AEG",
  ],
  "Electrical Hardware": [
    "Schneider Electric",
    "Siemens",
    "ABB",
    "Legrand",
    "Hager",
    "Eaton",
    "GE",
    "Panasonic",
    "Honeywell",
    "Bosch",
    "Leviton",
    "Philips",
    "Mersen",
    "Chint",
    "Hikoki",
    "TACKLIFE",
    "Ferm",
    "Worx",
    "AEG",
    "Black+Decker",
  ],
  "Building Materials": [
    "Lafarge",
    "Cemex",
    "HeidelbergCement",
    "CRH",
    "Vicat",
    "Saint-Gobain",
    "BASF",
    "Holcim",
    "Sika",
    "Tata Steel",
    "JSW",
    "ArcelorMittal",
    "Boral",
    "James Hardie",
    "Knauf",
    "Hanson",
    "Ash Grove",
    "CalPortland",
    "Lehigh Hanson",
    "Graymont",
  ],
  "Locks & Keys": [
    "Yale",
    "Kwikset",
    "Schlage",
    "Assa Abloy",
    "Baldwin",
    "Mul-T-Lock",
    "C.R. Laurence",
    "Häfele",
    "Hettich",
    "Sugatsune",
    "Blum",
    "Dorma",
    "Stanley",
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Hikoki",
    "TACKLIFE",
    "Worx",
  ],
  "Concrete Tools": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Hilti",
    "Metabo",
    "Milwaukee",
    "Porter-Cable",
    "Festool",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Skil",
    "AEG",
    "Stanley",
    "Craftsman",
    "Ryobi",
    "Black+Decker",
    "Hitachi",
    "Dewalt FlexVolt",
  ],
  "Workshop Tools": [
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Ryobi",
    "Black+Decker",
    "Festool",
    "Metabo",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "Stanley",
    "AEG",
    "Dewalt FlexVolt",
    "Makita Kit",
    "Bosch Kit",
  ],
  "Hardware Accessories": [
    "Häfele",
    "Assa Abloy",
    "Kwikset",
    "Schlage",
    "Yale",
    "Baldwin",
    "Hettich",
    "Sugatsune",
    "Blum",
    "Roto",
    "Dorma",
    "C.R. Laurence",
    "Stanley",
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Hikoki",
    "TACKLIFE",
    "Worx",
  ],
  Workbenches: [
    "Kreg",
    "WEN",
    "Bosch",
    "DeWalt",
    "Makita",
    "Milwaukee",
    "Ryobi",
    "Festool",
    "Porter-Cable",
    "Skil",
    "Craftsman",
    "Ferm",
    "Hikoki",
    "TACKLIFE",
    "Worx",
    "AEG",
    "Black+Decker",
    "Hitachi",
    "Dewalt FlexVolt",
    "Bosch Bench",
  ],

  // Lighting & Electrical
  "LED Bulbs": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Cree",
    "Feit Electric",
    "Sylvania",
    "Havells",
    "Syska",
    "Wipro",
    "Panasonic",
    "Eveready",
    "Toshiba",
    "LG",
    "Samsung",
    "Sharp",
    "Inesa",
    "Bajaj",
    "Osram India",
    "HPL",
    "V-Guard",
  ],
  "Tube Lights": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "V-Guard",
    "Eveready India",
    "HPL",
    "Inesa",
    "Sharp",
    "Surya",
  ],
  "Ceiling Lights": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Bajaj",
    "Panasonic",
    "Eveready",
    "Toshiba",
    "LG",
    "Samsung",
    "V-Guard",
    "Eveready India",
    "HPL",
    "Inesa",
    "Sharp",
    "Surya",
    "Feit Electric",
  ],
  Chandeliers: [
    "Philips",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Eglo",
    "Kichler",
    "Hinkley",
    "Schonbek",
    "Foscarini",
    "Vibia",
    "Inesa",
    "HPL",
  ],
  "Decorative String Lights": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Feit Electric",
    "Toshiba",
    "LG",
    "Samsung",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
  ],
  "Wall Lamps": [
    "Philips",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Eglo",
    "Kichler",
    "Hinkley",
    "Schonbek",
    "Foscarini",
    "Vibia",
    "Inesa",
    "HPL",
  ],
  "Switches & Sockets": [
    "Schneider Electric",
    "Legrand",
    "Havells",
    "MK Electric",
    "Panasonic",
    "ABB",
    "Siemens",
    "GE",
    "Eaton",
    "L&T",
    "Hager",
    "Clipper",
    "V-Guard",
    "Anchor",
    "Wipro",
    "Leviton",
    "Honeywell",
    "Bosch",
    "Toshiba",
    "Philips",
  ],
  "Extension Boards": [
    "Belkin",
    "Philips",
    "Anchor",
    "Syska",
    "Havells",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "GE",
    "Osram",
    "Toshiba",
    "LG",
    "Samsung",
    "V-Guard",
    "Surya",
    "Inesa",
    "HPL",
    "Feit Electric",
  ],
  "Solar Lights": [
    "Philips",
    "Syska",
    "Havells",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
    "GE Lighting",
    "Osram",
  ],
  "Emergency Lights": [
    "Philips",
    "Syska",
    "Havells",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
    "GE Lighting",
    "Osram",
  ],
  "Desk Lamps": [
    "Philips",
    "Syska",
    "Havells",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
    "GE Lighting",
    "Osram",
  ],
  "Flood Lights": [
    "Philips",
    "Syska",
    "Havells",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
    "GE Lighting",
    "Osram",
  ],
  "Outdoor Lighting": [
    "Philips",
    "Syska",
    "Havells",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
    "GE Lighting",
    "Osram",
  ],
  "Smart Lights": [
    "Philips Hue",
    "LIFX",
    "Yeelight",
    "TP-Link",
    "Sengled",
    "Nanoleaf",
    "GE Lighting",
    "Osram",
    "Cree",
    "Wipro",
    "Syska",
    "Havells",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "V-Guard",
  ],
  "Track Lighting": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Feit Electric",
    "Toshiba",
    "LG",
    "Samsung",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
  ],
  "Pendant Lights": [
    "Philips",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Eglo",
    "Kichler",
    "Hinkley",
    "Schonbek",
    "Foscarini",
    "Vibia",
    "Inesa",
    "HPL",
  ],
  "Recessed Lighting": [
    "Philips",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Eglo",
    "Kichler",
    "Hinkley",
    "Schonbek",
    "Foscarini",
    "Vibia",
    "Inesa",
    "HPL",
  ],
  "Night Lights": [
    "Philips",
    "Havells",
    "Syska",
    "Wipro",
    "Crompton",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Toshiba",
    "LG",
    "Samsung",
    "Feit Electric",
    "Eglo",
    "Kichler",
    "Hinkley",
    "Schonbek",
    "Foscarini",
    "Vibia",
    "Inesa",
    "HPL",
  ],
  "Stage Lighting": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Feit Electric",
    "Toshiba",
    "LG",
    "Samsung",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
  ],
  "Industrial Lighting": [
    "Philips",
    "Osram",
    "GE Lighting",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "Crompton",
    "Panasonic",
    "Feit Electric",
    "Toshiba",
    "LG",
    "Samsung",
    "Surya",
    "Inesa",
    "HPL",
    "Eglo",
    "Kichler",
    "Vibia",
  ],

  "USB Cables": [
    "Anker",
    "UGREEN",
    "Amazon Basics",
    "Belkin",
    "Syncwire",
    "iVANKY",
    "JSAUX",
    "CHOETECH",
    "Cable Matters",
    "Monoprice",
    "BlueRigger",
    "Apple",
    "Samsung",
    "Sony",
    "Xiaomi",
    "Huawei",
    "OnePlus",
    "Baseus",
    "TNP",
    "KabelDirekt",
  ],

  "Ethernet Cables": [
    "TP-Link",
    "Amazon Basics",
    "Cable Matters",
    "UGREEN",
    "Jadaol",
    "Vandesail",
    "Mediabridge",
    "Rosewill",
    "Belkin",
    "Monoprice",
    "C2G",
    "StarTech",
    "Netgear",
    "D-Link",
    "NETGEAR",
    "Siemon",
    "Panduit",
    "TRENDnet",
    "HDE",
    "KabelDirekt",
  ],
  "Audio Cables": [
    "Amazon Basics",
    "UGREEN",
    "Monoprice",
    "BlueRigger",
    "KabelDirekt",
    "Hosa",
    "Pro Co",
    "Rockville",
    "Mediabridge",
    "Seismic",
    "Belkin",
    "StarTech",
    "TNP",
    "CHOETECH",
    "Syncwire",
    "Anker",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
  ],
  "Charging Cables": [
    "Anker",
    "UGREEN",
    "Amazon Basics",
    "Belkin",
    "CHOETECH",
    "Baseus",
    "iVANKY",
    "JSAUX",
    "Syncwire",
    "Cable Matters",
    "Monoprice",
    "BlueRigger",
    "Apple",
    "Samsung",
    "Sony",
    "Xiaomi",
    "Huawei",
    "OnePlus",
    "TNP",
    "KabelDirekt",
  ],
  "Coaxial Cables": [
    "Amazon Basics",
    "Mediabridge",
    "Monoprice",
    "KabelDirekt",
    "BlueRigger",
    "C2G",
    "Belkin",
    "StarTech",
    "CHOETECH",
    "Syncwire",
    "TNP",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "HDE",
    "Pyle",
    "Bosch",
    "Anker",
    "UGREEN",
  ],
  "Fiber Optic Cables": [
    "TP-Link",
    "Amazon Basics",
    "Cable Matters",
    "Belkin",
    "UGREEN",
    "StarTech",
    "Monoprice",
    "CHOETECH",
    "iVANKY",
    "JSAUX",
    "BlueRigger",
    "Anker",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "TNP",
    "KabelDirekt",
    "HDE",
  ],
  "Cable Organizers": [
    "Velcro",
    "UGREEN",
    "Joto",
    "BlueRigger",
    "Anker",
    "Amazon Basics",
    "Cable Matters",
    "CHOETECH",
    "Monoprice",
    "Syncwire",
    "StarTech",
    "TNP",
    "KabelDirekt",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "Belkin",
  ],
  "Industrial Wires": [
    "Prysmian",
    "Southwire",
    "Havells",
    "Finolex",
    "Polycab",
    "Legrand",
    "Siemens",
    "ABB",
    "L&T",
    "V-Guard",
    "Philips",
    "Osram",
    "GE",
    "Bosch",
    "Wipro",
    "Syska",
    "Eveready",
    "Bajaj",
    "Panasonic",
    "Samsung",
  ],
  "AV Cables": [
    "Amazon Basics",
    "UGREEN",
    "Monoprice",
    "BlueRigger",
    "Cable Matters",
    "iVANKY",
    "CHOETECH",
    "Syncwire",
    "StarTech",
    "TNP",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "C2G",
    "Belkin",
    "Anker",
    "JSAUX",
  ],
  "Lightning Cables": [
    "Apple",
    "Anker",
    "UGREEN",
    "Amazon Basics",
    "CHOETECH",
    "Baseus",
    "iVANKY",
    "JSAUX",
    "Syncwire",
    "Cable Matters",
    "Monoprice",
    "BlueRigger",
    "Samsung",
    "Sony",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "TNP",
    "Belkin",
  ],
  "Type-C Cables": [
    "Anker",
    "UGREEN",
    "CHOETECH",
    "Baseus",
    "Amazon Basics",
    "JSAUX",
    "Syncwire",
    "Cable Matters",
    "Monoprice",
    "BlueRigger",
    "iVANKY",
    "Samsung",
    "Sony",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "TNP",
    "Belkin",
    "Apple",
  ],
  "Extension Cords": [
    "Belkin",
    "Amazon Basics",
    "GE",
    "Tripp Lite",
    "C2G",
    "Monoprice",
    "CyberPower",
    "APC",
    "Panasonic",
    "Philips",
    "Osram",
    "LG",
    "Samsung",
    "V-Guard",
    "Havells",
    "Syska",
    "Wipro",
    "Eveready",
    "Bajaj",
    "CHOETECH",
  ],
  "Speaker Wires": [
    "Amazon Basics",
    "Monoprice",
    "BlueRigger",
    "C2G",
    "Belkin",
    "StarTech",
    "Hosa",
    "Pro Co",
    "Rockville",
    "Mediabridge",
    "Seismic",
    "UGREEN",
    "Anker",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "TNP",
  ],
  "Network Cables": [
    "TP-Link",
    "Amazon Basics",
    "Cable Matters",
    "UGREEN",
    "Jadaol",
    "Vandesail",
    "Mediabridge",
    "Rosewill",
    "Belkin",
    "Monoprice",
    "C2G",
    "StarTech",
    "Netgear",
    "D-Link",
    "NETGEAR",
    "Siemon",
    "Panduit",
    "TRENDnet",
    "HDE",
    "KabelDirekt",
  ],
  "Monitor Cables": [
    "Amazon Basics",
    "Belkin",
    "UGREEN",
    "Anker",
    "Cable Matters",
    "BlueRigger",
    "Monoprice",
    "iVANKY",
    "JSAUX",
    "CHOETECH",
    "Syncwire",
    "StarTech",
    "TNP",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "C2G",
  ],
  "Adapter Cables": [
    "Anker",
    "UGREEN",
    "CHOETECH",
    "Baseus",
    "Amazon Basics",
    "JSAUX",
    "Syncwire",
    "Cable Matters",
    "Monoprice",
    "BlueRigger",
    "iVANKY",
    "Samsung",
    "Sony",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "TNP",
    "Belkin",
    "Apple",
  ],
  "Ribbon Cables": [
    "Amazon Basics",
    "UGREEN",
    "Monoprice",
    "BlueRigger",
    "Cable Matters",
    "iVANKY",
    "CHOETECH",
    "Syncwire",
    "StarTech",
    "TNP",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "C2G",
    "Belkin",
    "Anker",
    "JSAUX",
  ],
  "Flat Cables": [
    "Amazon Basics",
    "UGREEN",
    "Monoprice",
    "BlueRigger",
    "Cable Matters",
    "iVANKY",
    "CHOETECH",
    "Syncwire",
    "StarTech",
    "TNP",
    "Sony",
    "Samsung",
    "Philips",
    "LG",
    "Panasonic",
    "HDE",
    "C2G",
    "Belkin",
    "Anker",
    "JSAUX",
  ],

  // Gaming & Consoles
  "PlayStation Consoles": [
    "Sony",
    "Sony PlayStation",
    "Sony PS5",
    "Sony PS4",
    "Sony PS3",
    "Sony PS2",
    "Sony PS Vita",
    "Sony PS One",
    "Sony PSX",
    "Sony PS4 Pro",
    "Sony PS5 Digital",
    "Sony PS5 Disc",
    "Sony PS4 Slim",
    "Sony PS4 Standard",
    "Sony PS3 Slim",
    "Sony PS3 Standard",
    "Sony PS2 Slim",
    "Sony PS2 Standard",
    "Sony PS1",
    "Sony PS One Classic",
  ],
  "Xbox Consoles": [
    "Microsoft",
    "Xbox Series X",
    "Xbox Series S",
    "Xbox One",
    "Xbox One S",
    "Xbox One X",
    "Xbox 360",
    "Xbox 360 Slim",
    "Xbox 360 E",
    "Xbox Original",
    "Xbox Elite",
    "Xbox One Elite",
    "Xbox Series X Digital",
    "Xbox Series S Digital",
    "Xbox One Standard",
    "Xbox One S Digital",
    "Xbox One X Digital",
    "Xbox One S All-Digital",
    "Xbox One X All-Digital",
    "Xbox 360 Arcade",
  ],
  "Nintendo Switch": [
    "Nintendo",
    "Switch OLED",
    "Switch V2",
    "Switch Lite",
    "Switch Standard",
    "Switch Bundle",
    "Switch Neon",
    "Switch Gray",
    "Switch Red/Blue",
    "Switch Animal Crossing",
    "Switch Mario Kart",
    "Switch Zelda",
    "Switch Super Mario",
    "Switch Pokemon",
    "Switch Splatoon",
    "Switch Lite Neon",
    "Switch Lite Gray",
    "Switch Lite Blue",
    "Switch Lite Yellow",
    "Switch Lite Red",
  ],
  "Gaming PCs": [
    "Alienware",
    "MSI",
    "Asus ROG",
    "Acer Predator",
    "HP Omen",
    "Dell G Series",
    "Lenovo Legion",
    "CyberPowerPC",
    "iBUYPOWER",
    "Razer",
    "Corsair",
    "EVGA",
    "Gigabyte",
    "NZXT",
    "Origin PC",
    "Maingear",
    "Falcon Northwest",
    "ABS",
    "Velocity Micro",
    "Digital Storm",
  ],
  "Gaming Controllers": [
    "Sony DualShock",
    "Sony DualSense",
    "Microsoft Xbox Controller",
    "Nintendo Pro Controller",
    "Razer Wolverine",
    "Scuf Gaming",
    "PowerA",
    "8BitDo",
    "Thrustmaster",
    "Hori",
    "Logitech F310",
    "Logitech F710",
    "Victrix Pro",
    "Nacon",
    "PDP",
    "Brook",
    "SteelSeries",
    "Razer Raiju",
    "Razer Tartarus",
    "Hori Onyx",
  ],
  "Gaming Keyboards & Mice": [
    "Razer",
    "Logitech",
    "Corsair",
    "SteelSeries",
    "HyperX",
    "Asus ROG",
    "MSI",
    "Cooler Master",
    "EVGA",
    "Redragon",
    "Thermaltake",
    "ROCCAT",
    "Fnatic Gear",
    "Glorious",
    "Bloody",
    "Gigabyte",
    "Alienware",
    "Acer Predator",
    "HyperX Alloy",
    "SteelSeries Apex",
  ],
  "Gaming Chairs": [
    "DXRacer",
    "Secretlab",
    "AKRacing",
    "Anda Seat",
    "Noblechairs",
    "Corsair",
    "Vertagear",
    "GT Omega",
    "Cougar",
    "Arozzi",
    "X Rocker",
    "Homall",
    "Ficmax",
    "RESPAWN",
    "Herman Miller",
    "Autofull",
    "E-WIN",
    "Fantech",
    "ONEX",
    "Merax",
  ],
  "Game Discs & Digital Codes": [
    "Sony",
    "Microsoft",
    "Nintendo",
    "Steam",
    "Epic Games",
    "Ubisoft",
    "EA",
    "Activision",
    "Bethesda",
    "Square Enix",
    "Capcom",
    "Bandai Namco",
    "Rockstar Games",
    "Blizzard",
    "2K Games",
    "SEGA",
    "CD Projekt",
    "Valve",
    "Konami",
    "THQ",
  ],
  "Streaming Gear": [
    "Elgato",
    "Razer",
    "Logitech",
    "Corsair",
    "AverMedia",
    "Rode",
    "Blue Microphones",
    "HyperX",
    "Behringer",
    "Focusrite",
    "PreSonus",
    "AKG",
    "Shure",
    "AKRacing",
    "Manfrotto",
    "Neewer",
    "Blackmagic",
    "Sony",
    "Canon",
    "Panasonic",
  ],
  "VR Gaming Accessories": [
    "Oculus",
    "Meta Quest",
    "HTC Vive",
    "Valve Index",
    "Sony PlayStation VR",
    "Pimax",
    "Samsung Odyssey",
    "HP Reverb",
    "Windows Mixed Reality",
    "Lenovo Mirage",
    "VR Cover",
    "Vive Cosmos",
    "Oculus Rift",
    "Oculus Rift S",
    "Oculus Quest 2",
    "HTC Vive Pro",
    "Valve Index Controllers",
    "Sony PSVR Aim",
    "Razer OSVR",
    "Pimax Vision",
  ],
  "Arcade Machines": [
    "Sega",
    "Namco",
    "Atari",
    "Bally",
    "Williams",
    "Capcom",
    "Midway",
    "Data East",
    "Konami",
    "Taito",
    "Bandai Namco",
    "GameRoomSolutions",
    "ICE",
    "Happ Controls",
    "Innovative Concepts",
    "Golden Tee",
    "ARCADE1UP",
    "Neo Geo",
    "Universal",
    "Raw Thrills",
  ],
  "Game Capture Cards": [
    "Elgato",
    "AverMedia",
    "Razer",
    "Magewell",
    "Blackmagic Design",
    "Corsair",
    "Roland",
    "AVerMedia Live Gamer",
    "StarTech",
    "Mirabox",
    "Pengo",
    "Roxio",
    "Epiphan",
    "IOGEAR",
    "Hauppauge",
    "Blackmagic",
    "Elgato HD60",
    "Elgato 4K60",
    "AVerMedia GC551",
    "AVerMedia GC573",
  ],
  "Racing Wheels": [
    "Logitech",
    "Thrustmaster",
    "Fanatec",
    "Hori",
    "PXN",
    "SimXperience",
    "AccuForce",
    "Greenspeed",
    "Leo Bodnar",
    "VelociRaptor",
    "Fanatec CSL",
    "Fanatec ClubSport",
    "Thrustmaster T300",
    "Logitech G29",
    "Logitech G920",
    "Hori Racing Wheel",
    "PXN V3II",
    "SimXperience AccuForce Pro",
    "Fanatec Podium",
    "Thrustmaster TX",
  ],
  "Flight Sim Controllers": [
    "Thrustmaster",
    "Logitech",
    "Honeycomb",
    "CH Products",
    "Virpil",
    "VKB",
    "Saitek",
    "TM Warthog",
    "Thrustmaster HOTAS",
    "Logitech G X56",
    "Thrustmaster T.Flight",
    "CH Pro Throttle",
    "Honeycomb Alpha Flight",
    "VKB Gunfighter",
    "TM Warthog HOTAS",
    "Saitek X52",
    "Saitek X56",
    "VKB Gladiator",
    "Honeycomb Bravo Throttle",
    "Logitech G Flight Yoke",
  ],
  "Gaming Headsets": [
    "HyperX",
    "SteelSeries",
    "Razer",
    "Logitech",
    "Corsair",
    "Astro",
    "Turtle Beach",
    "Sennheiser",
    "Plantronics",
    "Beyerdynamic",
    "Sony",
    "Microsoft",
    "EPOS",
    "Creative",
    "Roccat",
    "Cooler Master",
    "Asus ROG",
    "MSI",
    "Roccat Khan",
    "ROG Delta",
  ],
  "Gaming Desks": [
    "Arozzi",
    "Eureka Ergonomic",
    "Respawn",
    "Atlantic",
    "DXRacer",
    "Cougar",
    "Vitesse",
    "FlexiSpot",
    "Mr IRONSTONE",
    "Coleshome",
    "Vitesse Gaming Desk",
    "DXRacer Gaming Desk",
    "Arozzi Arena",
    "Eureka Ergonomic Z1",
    "Respawn 3010",
    "Cougar Mars",
    "FlexiSpot E7",
    "Atlantic Gaming Desk",
    "Mr IRONSTONE Desk",
    "Coleshome Gaming Desk",
  ],
  "Graphics Cards for Gaming": [
    "NVIDIA",
    "AMD",
    "ASUS",
    "MSI",
    "Gigabyte",
    "EVGA",
    "ZOTAC",
    "Sapphire",
    "PNY",
    "Palit",
    "GALAX",
    "PowerColor",
    "Colorful",
    "Inno3D",
    "Gainward",
    "Manli",
    "KFA2",
    "XFX",
    "PNY GeForce",
    "MSI Gaming",
  ],
  "Cooling Fans for Gaming PCs": [
    "Noctua",
    "Corsair",
    "Cooler Master",
    "be quiet!",
    "NZXT",
    "Thermaltake",
    "ARCTIC",
    "Scythe",
    "Deepcool",
    "Fractal Design",
    "BitFenix",
    "Phanteks",
    "Enermax",
    "SilverStone",
    "Akasa",
    "Antec",
    "COOLJOY",
    "Cougar",
    "Jonsbo",
    "Raijintek",
  ],
  "LED Gaming Lights": [
    "Corsair",
    "NZXT",
    "Thermaltake",
    "Razer",
    "Govee",
    "Philips Hue",
    "Antec",
    "Cooler Master",
    "HyperX",
    "Logitech",
    "Elgato",
    "Asus ROG",
    "MSI",
    "Cooler Master MasterFan",
    "BitFenix",
    "Fractal Design",
    "Deepcool",
    "Razer Chroma",
    "Govee Dreamcolor",
    "LIFX",
  ],
  "Gamepads & Joysticks": [
    "Sony DualShock",
    "Sony DualSense",
    "Microsoft Xbox Controller",
    "Nintendo Pro Controller",
    "Razer Wolverine",
    "8BitDo",
    "Thrustmaster",
    "Hori",
    "Logitech F310",
    "Logitech F710",
    "Victrix Pro",
    "Nacon",
    "PDP",
    "Brook",
    "SteelSeries",
    "Razer Raiju",
    "Razer Tartarus",
    "Hori Onyx",
    "PowerA Fusion",
    "Scuf Gaming",
  ],
};


export type AllCategoryName = keyof typeof allBrands
export type AllBrendName =  typeof allBrands[AllCategoryName][number]  



export const defaultReviewsValues = {
  name: "",
  rating: 0,
  comment: "",
};